name: my_new_project
version: '1.0.0'
config-version: 2

# Profile name from profiles.yml
profile: default

# Where dbt looks for different resources
model-paths: 
  - healthcare782025/models
  - SLEEKMART_OMS_L1_LANDING/models
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Where compiled files go
target-path: "target"

# Folders to delete with dbt clean
clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations
models:
  healthcare782025:  
    +materialized: table
  SLEEKMART_OMS_L1_LANDING:  
    +materialized: table